SELECT * FROM  customer
GO

--Q1. What is the total revenue generated by male vs female customers?
SELECT gender AS Genero, SUM(purchase_amount) AS Ganancia
FROM customer
GROUP BY gender
GO

--Q2. Which customers used a discount but still spent more than the average purchase amount
SELECT customer_id AS ID_Cliente, purchase_amount
FROM customer
WHERE discount_applied='Yes' AND purchase_amount>(SELECT AVG(purchase_amount)FROM customer)
GO

--Q3. Which are the top 5 products with the highest average review rating?

SELECT TOP 5 item_purchased AS Producto, ROUND(AVG(review_rating),2) AS Rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
GO

--Q4. Compare the average purchase amounts between Standar and Express Shipping.

SELECT shipping_type AS [Tipo de Envío], ROUND(AVG(purchase_amount),2) AS [Average Purchase Amount]
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type
GO

-- Q5. Do suscribed customers spend more? Compare average spend and total revenue 
--between suscribers and non-suscribers.
SELECT subscription_status AS Suscriptor, AVG(purchase_amount) AS Average_Spend, 
SUM(purchase_amount) AS Ganancia_Total,COUNT(customer_id) AS Población
FROM customer
GROUP BY subscription_status                
GO

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 
    item_purchased AS Producto, 
    -- Al usar 100.00 (decimal), SQL activa los decimales para toda la operación
    CAST(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS DECIMAL(10,2)) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
GO

--Q7. Segment customers into Now, Returning, and Loyal based on their total
--number of previous purchases, and show the count of each segment.
WITH Customer_type as (
SELECT customer_id, previous_purchases,
CASE	
	WHEN previous_purchases= 1 THEN 'New'
	WHEN previous_purchases between 2 and 10 THEN 'Returning'
	ELSE 'loyal'
	END AS customer_segment
FROM customer
)
SELECT customer_segment, Count(*) AS 'Number of Customers'
FROM Customer_type
GROUP BY customer_segment
GO

--Q8. What are the top 3 most purchased products within each category?
WITH Item_Counts AS (
SELECT  category, item_purchased, COUNT(customer_id) AS total_orders,
ROW_NUMBER()OVER(PARTITION BY category ORDER BY Count(customer_id) DESC) AS Item_Rank
FROM customer
GROUP BY category, item_purchased
)
SELECT *
FROM Item_Counts
WHERE Item_Rank<=3
GO

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS Repeat_Buyers
FROM customer
WHERE previous_purchases>5
GROUP BY subscription_status
GO

--Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS Contribution
FROM customer
GROUP BY age_group
ORDER BY Contribution DESC
GO